FROM quay.io/jvdbreggen/demolab-rhel:latest

RUN dnf -y install httpd

ADD etc/ /etc

RUN <<EOF 
    set -euxo pipefail
    mv /var/www /usr/share/www
    sed -i 's-/var/www-/usr/share/www-' /etc/httpd/conf/httpd.conf
EOF
  
ADD html/ /usr/share/www/html

RUN cp /etc/redhat-release /usr/share/www/html/redhat-release
RUN cp /etc/os-release /usr/share/www/html/os-release
RUN uname -sr > /usr/share/www/html/uname.txt

RUN systemctl enable httpd 

EXPOSE 80
