FROM quay.io/jvdbreggen/demolab-rhel:latest

ADD html/ /usr/share/www/html

ADD etc/ /etc

RUN cp /etc/redhat-release /usr/share/www/html/redhat-release
RUN cp /etc/os-release /usr/share/www/html/os-release
RUN uname -sr > /usr/share/www/html/uname.txt

EXPOSE 80
