MAINTAINER Alessandro Rossi <al.rossi87@gmail.com>
FROM registry.redhat.io/rhel10/rhel-bootc:9.4
RUN dnf -y update && dnf -y install tmux mkpasswd insights-client
RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 redhat) && useradd -m -G wheel bootc-user -p $pass
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo
RUN echo "This is a RHEL 10 VM installed using a bootable container with Red Hat Insights installed!" > /etc/motd.d/10-first-setup.motd
RUN echo "The VM was updated using a newer version of the image" > /etc/motd.d/20-update.motd
