FROM registry.redhat.io/rhel10/rhel-bootc:10.1
LABEL org.opencontainers.image.authors="alerossi@redhat.com"
RUN dnf -y install tmux mkpasswd
RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 redhat) && useradd -m -G wheel bootc-user -p $pass
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo
